# -*- coding: utf-8 -*-
"""Project 01 - Churn rate EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7xK38JyoFikCmLcQqH-NoCxVWs0yVDo

# **Import Libraries**
We will use the following libraries
1. Pandas: Data manipulation and analysis
2. Numpy: Numerical operations and calculations
3. Matplotlib: Data visualization and plotting
4. Seaborn: Enhanced data visualization and statistical graphics
5. Scipy: Scientific computing and advanced mathematical operations
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp

"""# Loading Data & Exploration"""

# Load a CSV file then creating a dataframe
df = pd.read_excel('/content/drive/MyDrive/DAC 6 month - Unigap/Copy of churn_prediction.xlsx')

# Set the option to show maximum columns
pd.set_option('display.max_columns', None)

# Get a sneak peek of data
df.head()

# Look at the shape of the data
print(f'The number of rows are {df.shape[0]}, and the columns are {df.shape[1]}')

# Overview the data types
df.info()

# Look at columns with null values
df.isnull().sum()

"""## **Observation set 1**
* There are 5630 rows, and 20 columns in the dataset
* The data type of all columns is acceptable
* There are a few missing values in the dataset: Tenure, WarehouseToHome, HourSpendOnApp, OrderAmountHikeFromlastYear, CouponUsed, OrderCount, DaySinceLastOrder. They will be read in detail and deal with

## **Dealing with the missing values**
Dealing with the missing values is one of the most important part of the data wrangling process, we must deal with the missing values in order to get the correct insights from the data.¶
"""

#Missing value clearing step 1: calculate 5% missing values can be dropped threshold:
threshold = len(df) * 0.05
print(threshold)

#Missing value clearing step 2: calculate total rows with missing values rows
rows_with_nulls = df.isnull().any(axis=1).sum()
print(rows_with_nulls <= threshold)

#Missing value clearing step 3: As the rows with nulls is greater than threshold, we will fill null value with median
cols_with_null = ['Tenure', 'WarehouseToHome', 'HourSpendOnApp', 'OrderAmountHikeFromlastYear', 'CouponUsed', 'OrderCount', 'DaySinceLastOrder']
df[cols_with_null] = df[cols_with_null].fillna(df[cols_with_null].median())

#Missing value clearing step 4: Check null values after addressing
df.isnull().sum()

"""### **Milestone 1: We have cleaned the dataset from null values**

## **Find Duplications and Analyse them**
*   Removing duplicates is one of the most important part of the data wrangling process, we must remove the duplicates in order to get the correct insights from the data.
*   Duplicates can skew statistical measures such as mean, median, and standard deviation, and can also lead to over-representation of certain data points.
"""

df[df.duplicated(subset=['CustomerID'], keep = False)]

"""### **Milestone 2: No duplicates found**

## **Descriptive statistic**
"""

df.describe()

num_cols = ['Tenure', 'WarehouseToHome',
            'OrderAmountHikeFromlastYear', 'CouponUsed',
            'OrderCount', 'DaySinceLastOrder', 'CashbackAmount']

fig, axes = plt.subplots(3, 3, figsize=(20, 20))
axes = axes.flatten()

for i, col in enumerate(num_cols):
    axes[i].boxplot(df[col], showmeans = True)
    axes[i].set_title(col, fontsize=13)

plt.show()

# Look at the categorical columns
cat_cols = ['Churn','PreferredLoginDevice','CityTier',
            'PreferredPaymentMode', 'Gender','HourSpendOnApp',
            'NumberOfDeviceRegistered', 'PreferedOrderCat','SatisfactionScore',
            'MaritalStatus', 'NumberOfAddress','Complain']

fig, axes = plt.subplots(4, 3, figsize=(20, 20))
axes = axes.flatten()

for i, col in enumerate(cat_cols):
    df[col].value_counts().plot(kind='bar', ax=axes[i])
    axes[i].set_title(col)

plt.tight_layout()
plt.show()

# Addressing inconsistent labeling in 2 columns — "Phone" and "Mobile Phone" in PreferredLoginDevice; "Mobile" and "Mobile Phone" in PreferedOrderCat
df['PreferredLoginDevice'] = df['PreferredLoginDevice'].replace('Phone', 'Mobile Phone')
df['PreferedOrderCat'] = df['PreferedOrderCat'].replace('Mobile', 'Mobile Phone')

fig, axes = plt.subplots(4, 3, figsize=(20, 20))
axes = axes.flatten()

for i, col in enumerate(cat_cols):
    df[col].value_counts().plot(kind='bar', ax=axes[i])
    axes[i].set_title(col)

plt.tight_layout()
plt.show()

"""## Milestone 3: Replace incorrect values
* Replaced Phone to Mobile phone in PreferredLoginDevice column
* Replace Mobile to Mobile phone in PreferredOrderCat column

## **Analysis Churn rate**
"""

# Churn percentage
print(df['Churn'].value_counts(normalize=True) * 100)

"""In our dataset, approximately 17% of customers were flagged as a potential churn."""

fig, axes = plt.subplots(3, 3, figsize=(18, 15))
axes = axes.flatten()

for i, col in enumerate(num_cols):
    df.boxplot(column=col, by='Churn', ax=axes[i])
    axes[i].set_title(col)

plt.tight_layout()
plt.show()

"""*   Tenure shows the clearest separation between groups — churn flagged customers tend to have low tenure (roughly 1–8 months)
*   Other numerical variables show no meaningful difference between the two groups.






"""

fig, axes = plt.subplots(4, 3, figsize=(16, 18))
axes = axes.flatten()

for i, col in enumerate(cat_cols):
    ct = pd.crosstab(df[col], df['Churn'], normalize='index') * 100
    ct.plot(kind='bar', stacked=True, ax=axes[i])
    axes[i].set_ylabel('%')
    axes[i].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

"""Higher churn rates were found among customer with below charateristics:
*  Prefered payment mode: COD, Ewallet
*  Number of deviced registerd: 5 to 6
*  Prefered orther category: Mobile phone
*  Marital status: Single
*  Complain: filled complaint
"""

plt.figure(figsize=(14, 10))
corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', center=0)
plt.title('Correlation Heatmap')
plt.show()

"""Based on all above charts, we can conclude that:
*   Tenure shows the strongest negative correlation with churn (r = -0.35) — confirming that lower tenure means higher churn risk.
*   Complain shows a moderate positive correlation with churn (r = 0.25) — consistent with the pattern observed in Step 3.2

# Recommendations
1. Prioritize retaining new customers (Low Tenure):
- Tenure is the strongest predictor of churn — customers in their first 6 months carry the highest churn risk.
- Launch a dedicated onboarding program with special incentives during the first 3 months to build early loyalty.
- Focus retention efforts on Single customers, who show a disproportionately higher churn rate compared to other
  marital status groups.

2. Resolve complaints faster:
- Customers who filed a complaint churn at approximately 3x the rate of those who didn't — making complaint handling a critical retention lever.
- Reduce complaint response time and implement a structured follow-up process after resolution to rebuild customer trust.

3. Re-engage Mobile Phone category buyers:
- Customers who prefer the Mobile Phone category show a higher churn rate — suggesting they may make a one-time purchase and disengage before developing a shopping habit.
- Introduce post-purchase promotions (e.g. discount on next order, accessory bundles) in the days following a Mobile Phone purchase to encourage repeat engagement and build long-term shopping habits on the platform.
"""